# Generated by Django 3.1.7 on 2021-03-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_timestamp', models.DateTimeField(auto_now_add=True)),
                ('regidter_update', models.DateTimeField(auto_now=True)),
                ('frist_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('personal_email', models.EmailField(max_length=254)),
                ('cell_phone', models.CharField(blank=True, max_length=10)),
                ('local_phone', models.CharField(blank=True, max_length=10)),
                ('marketing_strategy', models.CharField(choices=[('FACEBOOK', 'FACEBOOK'), ('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER'), ('OTHERS', 'OTHERS')], max_length=32)),
                ('contacted', models.BooleanField(default=False)),
                ('captured', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.agent')),
            ],
        ),
    ]
