# Generated by Django 3.1.7 on 2021-03-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurante', models.CharField(max_length=30)),
                ('Correo_Local', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.CharField(max_length=10)),
            ],
        ),
    ]
