# Generated by Django 3.1.7 on 2021-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paisajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Lugar', models.CharField(max_length=30)),
                ('turismo', models.CharField(max_length=30)),
                ('artifical_natural', models.CharField(max_length=10)),
            ],
        ),
    ]
